django_projects/django_merchex-project/merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path

from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:id>/change/', views.band_update, name='band-update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),

    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:id>/', views.listing_detail, name='listing-detail'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('listings/<int:id>/change/', views.listing_update, name='listing-update'),
    path('listings/<int:id>/delete/', views.listing_update, name='listing-delete'),

    path('about-us/', views.about, name='about'),
    path('contact-us/', views.contact, name='contact'),
    path('email-sent/', views.email_sent),
]

django_projects/django_merchex-project/merchex/listings/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
       validators=[MinValueValidator(1900),
                   MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)


class Listing(models.Model):

    class ListingType(models.TextChoices):
        RECORDS = 'R'
        CLOTHING = 'C'
        POSTERS = 'P'
        MISC = 'M'

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        null=True,
        validators=[MinValueValidator(1900),
                    MaxValueValidator(2021)]
    )
    type = models.fields.CharField(choices=ListingType.choices, max_length=5)

django_projects/django_merchex-project/merchex/listings/forms.py
from django import forms

from listings.models import Band, Listing


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField()


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        exclude = ('active', 'official_homepage')


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = '__all__'

django_projects/django_merchex-project/merchex/listings/views.py
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from listings.models import Band, Listing
from listings.forms import BandForm, ContactUsForm, ListingForm


def band_list(request):
    bands = Band.objects.all()
    return render(request,
                  'listings/band_list.html',
                  {'bands': bands})


def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request,
                  'listings/band_detail.html',
                  {'band': band})


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # Création d'un nouveau 'Band' (groupe) et sauvegarde dans la base de données
            band = form.save()
            # Redirection vers la page de détail correspondant au groupe que nous venons de créer
            return HttpResponseRedirect(reverse('band-detail', kwargs={'id': band.id}))
    else:
        form = BandForm()

    return render(request,
                  'listings/band_create.html',
                  {'form': form})


def band_update(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # Mise à jour du groupe existant dans la base de données
            form.save()
            # Redirection vers la page de détail correspondant au groupe que nous venons de mettre à jour
            return HttpResponseRedirect(reverse('band-detail', kwargs={'id': band.id}))
    else:
        form = BandForm(instance=band)

    return render(request,
                  'listings/band_update.html',
                  {'form': form})


def band_delete(request, id):
    band = Band.objects.get(id=id)  # Nous en avons besoin pour les méthodes GET et POST

    if request.method == 'POST':
        # Suppression du groupe dans la base de données
        band.delete()
        # Redirection vers la liste des groupes
        return HttpResponseRedirect(reverse('band-list'))

    # Pas besoin d'un 'else' ici. Si il s'agit d'une requête GET continuant le programme tout simplement

    return render(request,
                  'listings/band_delete.html',
                  {'band': band})


def listing_list(request):
    listings = Listing.objects.all()
    return render(request,
                  'listings/listing_list.html',
                  {'listings': listings})


def listing_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request,
                  'listings/listing_detail.html',
                  {'listing': listing})


def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/listings/')
    else:
        form = ListingForm()

    return render(request,
                  'listings/listing_create.html',
                  {'form': form})


def listing_update(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST':
        form = ListingForm(request.POST, instance=band)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(f'/listings/{id}/')
    else:
        form = ListingForm(instance=band)

    return render(request,
                  'listings/listing_update.html',
                  {'form': form})


def listing_delete(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST':
        listing.delete()
        return HttpResponseRedirect(reverse('listing-list'))

    return render(request,
                  'listings/listing_delete.html',
                  {'listing': listing})


def about(request):
    return render(request, 'listings/about.html')


def contact(request):
    if request.method == 'POST':
        # Création d'une instance de notre formulaire et remplissage de ce dernier avec les données du POST
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonymous"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
            return HttpResponseRedirect('/email-sent/')
        # Si le formulaire n'est pas valide, nous devons continuons le programme en éxécutons le return

    else:
        # Ceci devrait être une requête GET, du coup nous créons un formulaire vide
        form = ContactUsForm()

    return render(request,
                  'listings/contact.html',
                  {'form': form})

def email_sent(request):
    return render(request, 'listings/email_sent.html')

django_projects/django_merchex-project/merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>À propos de nous</h1>

  <p>Nous adorons merch !</p>

{% endblock %}

django_projects/django_merchex-project/merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Créer un nouveau groupe</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Soumettre">
  </form>

{% endblock %}

django_projects/django_merchex-project/merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Effacer un groupe</h1>

  <p>Êtes-vous sûr de vouloir supprimer ce groupe ? : {{ band.name }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
  </form>

{% endblock %}

django_projects/django_merchex-project/merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>{{ band.name }}</h1>

  <ul>
    <li>Genre : {{ band.get_genre_display }}</li>
    <li>Année de création : {{ band.year_formed }}</li>
    <li>Actif : {{ band.active|yesno }}</li>
    {% if band.official_homepage %}
      <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
    {% endif %}
  </ul>

  <p>{{ band.biography }}</p>

  <a href="{% url 'band-update' band.id %}">Éditer un groupe</a>
  <a href="{% url 'band-delete' band.id %}">Supprimer un groupe</a>
  <a href="{% url 'band-list' %}">Retourner à la liste des groupes</a>

{% endblock %}

django_projects/django_merchex-project/merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Groupes</h1>

  <a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

  <ul>
    {% for band in bands %}
      <li>
        <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
        - <a href="{% url 'band-update' band.id %}">[Éditer]</a>
      </li>
    {% endfor %}
  </ul>

{% endblock %}

django_projects/django_merchex-project/merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Mettre à jour un groupe</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Soumettre">
  </form>

{% endblock %}

django_projects/django_merchex-project/merchex/listings/templates/listings/base.html
{% load static %}
<html>
  <head>
    <title>Merchex</title>
    <link rel="stylesheet" href="{% static 'listiings/style.css'%}" />
  </head>
  <body>

    <nav>
      <a href="{% url 'band-list' %}">Groupes</a>
      <a href="{% url 'listing-list' %}">Liste</a>
      <a href="{% url 'about' %}">À propos de nous</a>
      <a href="{% url 'contact' %}">Contactez nous</a>
    </nav>

     {% block content %}{% endblock %}

  </body>
</html>

django_projects/django_merchex-project/merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Contactez nous</h1>

  <p>Nous sommes là pour vous aider</p>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Soumettre">
  </form>

{% endblock %}

django_projects/django_merchex-project/merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Email envoyé</h1>

  <p>Nous revenons vers vous très vite.</p>

{% endblock %}

django_projects/django_merchex-project/merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Créer une nouvelle  liste</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Soumettre">
  </form>

{% endblock %}

django_projects/django_merchex-project/merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Effacer une liste</h1>

  <p>Êtes-vous sûr de vouloir supprimer cette liste ? : {{ listing.title }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
  </form>

{% endblock %}

django_projects/django_merchex-project/merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}

  <h2>{{ listing.title }}</h2>

  <ul>
    <li>Type: {{ listing.get_type_display }}</li>
    <li>Année d'origine : {{ listing.year }}</li>
    <li>Solde : {{ listing.sold|yesno }}</li>
  </ul>

  <p>{{ listing.description }}</p>

  <a href="{% url 'listing-update' band.id %}">Éditer cette liste</a>
  <a href="{% url 'listing-delete' listing.id %}">Supprimer cette liste</a>
  <a href="{% url 'listing-list' %}">Retourner à l'ensemble des listes</a>

{% endblock %}

django_projects/django_merchex-project/merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Listes</h1>

  <p>Jetez un oeil aux dernières listes en dessous !</p>

  <ul>
    {% for listing in listings %}
      <li>
        <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a>
        - <a href="{% url 'listing-update' listing.id %}">[Éditer]</a>
      </li>
    {% endfor %}
  </ul>

{% endblock %}

django_projects/django_merchex-project/merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Mettre à jour une liste</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Soumettre">
  </form>

{% endblock %}