django_projects/django_blog-main/src/blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_projects/django_blog-main/src/posts/urls.py
from django.urls import path
from posts.views import BlogHome, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete

app_name = "posts"

urlpatterns = [
    path('', BlogHome.as_view(), name='home'),
    path('create/', BlogPostCreate.as_view(), name='create'),
    path('<str:slug>/', BlogPostDetail.as_view(), name='post'),
    path('modifier/<str:slug>/', BlogPostUpdate.as_view(), name='edit'),
    path('delete/<str:slug>/', BlogPostDelete.as_view(), name='delete'),
]

django_projects/django_blog-main/src/posts/models.py
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.db import models
from django.urls import reverse

User = get_user_model()


class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name="Titre")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name="Publié")
    content = models.TextField(blank=True, verbose_name="Contenu")
    thumbnail = models.ImageField(blank=True, upload_to='blog')

    class Meta:
        ordering = ['-created_on']

        verbose_name = "Article"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

    @property
    def author_or_default(self):
        return self.author.username if self.author else "L'auteur inconnu"

    def get_absolute_url(self):
        return reverse('posts:home')

django_projects/django_blog-main/src/posts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from posts.models import BlogPost


class BlogHome(ListView):
    model = BlogPost
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset

        return queryset.filter(published=True)


@method_decorator(login_required, name='dispatch')
class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = "posts/blogpost_create.html"
    fields = ['title', 'content', ]


class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = "posts/blogpost_edit.html"
    fields = ['title', 'content', 'published', ]


class BlogPostDetail(DetailView):
    model = BlogPost
    context_object_name = "post"


class BlogPostDelete(DeleteView):
    model = BlogPost
    context_object_name = "post"
    success_url = reverse_lazy("posts:home")

django_projects/django_blog-main/src/posts/templates/posts/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
<title>Supprimer un article</title>
{% endblock %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        <p>Êtes-vous sûr de vouloir supprimer "{{ post.title }}"?</p>

        <input type="submit" value="Oui, supprimer" class="btn btn-delete">
    </form>

{% endblock %}

django_projects/django_blog-main/src/posts/templates/posts/blogpost_create.html
{% extends 'base.html' %}

{% block title %}
<title>Ajouter un article</title>
{% endblock %}

{% block content %}

<h1>Ajouter un article</h1>

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Créer" class="btn btn-submit">
</form>

{% endblock %}

django_projects/django_blog-main/src/posts/templates/posts/blogpost_detail.html
{% extends 'base.html' %}

{% block title %}
    <title>{{ post.title }}</title>
{% endblock %}

{% block content %}
    <article class="post-detail">
        <h1>{{ post.title }}</h1>
        <img src="{{ post.thumbnail.url }}" alt="L'image de l'article">
        <div>{{ post.content|safe }}</div>
    </article>
{% endblock %}

django_projects/django_blog-main/src/posts/templates/posts/blogpost_edit.html
{% extends 'base.html' %}

{% block title %}
    <title>Éditer un article</title>
{% endblock %}

{% block content %}

    <h1>Éditer l'article</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Éditer" class="btn btn-submit">
    </form>

{% endblock %}

django_projects/django_blog-main/src/posts/templates/posts/blogpost_list.html
{% extends 'base.html' %}

{% block title %}
<title>Accueil du blog</title>
{% endblock %}

{% block content %}

<h1>Le blog de Docstring</h1>
{% for post in posts %}
<article>

    <div class="post-title">
        <h2>{{ post.title }}</h2>
        {% if request.user.is_authenticated %}
        <div>
            <a href="{% url 'posts:edit' slug=post.slug %}">Éditer</a>
            <a href="{% url 'posts:delete' slug=post.slug %}">Supprimer</a>
        </div>
        {% endif %}
    </div>

    <h5 class="post-author">Publié par <i>{{ post.author_or_default }}</i> le {{ post.created_on|date:'j F Y' }}</h5>
    <p class="post-excerpt">{{ post.content|safe|truncatewords:50 }}</p>

    <form action="{% url 'posts:post' slug=post.slug %}">
        <button class="btn btn-submit">Lire l'article</button>
    </form>

</article>
{% endfor %}

{% endblock %}

django_projects/django_blog-main/src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<nav>
    <a href="{% url 'posts:home' %}">Accueil</a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'posts:create' %}">Ajouter un article</a>
    {% endif %}
</nav>

<section id="blog">
    {% block content %}
    {% endblock %}
</section>

</body>
</html>